version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.119.0"
    
phases:
  install:
    runtime-versions:
      docker: 19
    commands:                                                                 
      - cd /tmp
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-arm64.tar.gz
      - tar -xzf hugo_${HUGO_VERSION}_linux-arm64.tar.gz
      - mv hugo /usr/bin/hugo
      - cd - 
      - rm -rf /tmp/*
  build:
    commands:
      - cd ./hugo-app
      - rm -rf public
      - hugo
      - aws s3 sync public/ s3://hugo-app/?region=eu-north-1 --delete
  post_build:
    commands:
      - echo Build completed on `date`